### ISSUE TITLE
スコアリングモジュールIF_and_スコア結合部作成

### ISSUE THREAD

**Issue by y2klink** [Smart-SE/sse2019-group2#18]
# IF定義

* input
pyhton /usr/bin/scoring_if.py　-B 拍数 -f {録音した音楽ファイルのファイルパス}
  * 引数仕様
    * 拍数:0以上 
    *  録音した音楽ファイルのファイルパス: 
 * なお、コマンド側で値やファイルパスのチェックはしない予定

* output
スコア
  * 出力仕様:0～100

## 紐づけUS
#16

**Comment by y2klink** [comment]
初版をpushしました。

https://github.com/Smart-SE/sse2019-group2/blob/master/scoring/scoring_if.py

至らないところあれば、適当に変更してかまいません。
＝＞奥谷さん、all

**Comment by OKUYADaisuke** [comment]
奥谷モジュールを呼び出せるように修正しました

**Comment by y2klink** [comment]
吉田モジュール用の修正＋吉田モジュールが変な挙動しても奥谷さんモジュールのスコアを返せるようにしました。

**Comment by y2klink** [comment]
安全策のための、制御ファイルによる切り替え処理を実装完了
